### ISSUE TITLE
Building on nixpkgs, issue with goocanvas2

### ISSUE THREAD

**Issue by CMCDragonkai** [csete/gpredict#123]
Hi, I'm trying to package this up for nixpkgs.

I noticed that this package depends on goocanvas 2.

Nixpkgs master currently has goocanvas 2.0.4: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/goocanvas/2.x.nix

But the build still doesn't work.

What exact version does gpredict require for libgoocanvas-2.0-dev?

See: https://ftp.gnome.org/pub/gnome/sources/goocanvas/2.0/ for the various versions available.

**Comment by CMCDragonkai** [comment]
Seems to have solved it. I just needed to also bring in gtk3, not just goocanvas2.

**Comment by csete** [comment]
http://gpredict.oz9aec.net/User_Support.php
