### ISSUE TITLE
Incomplete transponders even after update transponder data

### ISSUE THREAD

**Issue by minecraft2048** [csete/gpredict#124]
For example NOAA 19 have HRPT and APT in https://www.wmo-sat.info/oscar/satellites/view/341 but only APT in Gpredict

**Comment by csete** [comment]
Data is imported from the Satnogs database, so please suggest the update there: https://db.satnogs.org/
It is not realistic to expect me to keep all data up to date.

**Comment by csete** [comment]
FYI I have updated the frequencies in the SatNOGS database, so if you fetch again you should have the HRPT frequencies for NOAA 15, 18 and 19.
