### ISSUE TITLE
Rotator controller doesn't work on Windows

### ISSUE THREAD

**Issue by csete** [csete/gpredict#128]
https://community.libre.space/t/gpredict-hangs-when-engaging-antenna-control-windows/1950/10

**Comment by csete** [comment]
Fix applied. Will close issue when we have a windows binary.

**Comment by tomvdb** [comment]
Has a new binary been built with this fix by any chance? Latest windows release binary giving me issues on rotator control and I'm not sure if it's this or something else.

**Comment by csete** [comment]
> Has a new binary been built with this fix by any chance?

I know my English is not very good, but exactly which part of "Will close issue when we have a windows binary" do you not understand?

**Comment by tomvdb** [comment]
Fair enough, just checking since it's been a while since that comment and was just excited about a new controller i'm making :) I've used the version under linux and it works perfect.

Thanks for the reply

**Comment by W3AXL** [comment]
Is there any good way to compile the newer versions on our own for windows? I could really use rotator control for our club and I've been trying all evening to compile using MSYS2/Mingw to no avail.

Alternatively is there any ideas on how soon 2.4 builds for windows will be out?

**Comment by csete** [comment]
@tomvdb  @W3AXL please try https://github.com/csete/gpredict/releases/download/v2.3/gpredict-win32-2.3.37.zip

Sorry for the late build.
