### ISSUE TITLE
Gpredict not obtaining transponder information.

### ISSUE THREAD

**Issue by masterplayer30** [csete/gpredict#152]
To whom may concern:

I use Gpredict on Ubuntu 16.04 using the official PPA from Launchpad. 

Sometimes when I do use the Gpredict software and I updated the transponder data and when I look for transponder info for the satellite it will say there is none when I know there is.

Is there anthing you can do to fix this.

Bobby Burgess

![screenshot_2018-11-21_12-26-05](https://user-images.githubusercontent.com/40179933/48861193-a71f9480-ed88-11e8-9176-02e75a92a347.png)

**Comment by csete** [comment]
Do you mean that the transponder information disappears, or that there never has been any transponder data for a specific satellite?

**Comment by masterplayer30** [comment]
Recentily I just redid my Ubuntu installation and put back GPredict and it did that. But I ran GPredict as root and it was able to obtain transponder information then. So I guess I can close it out for now.

**Comment by italic-r** [comment]
I am also having trouble getting transponder data. However, even manually downloading the json files from db.satnogs.org doesn't help. I can look at the file and all the data is there, but trying to view data in gpredict doesn't show anything. I thought it was just because AO-95 is new, but SO-50 and others don't show either. I downloaded both `modes.json` and `transmitters.json` and put them in `~/.config/Gpredict/trsp/`, but no dice. This is using release 2.2.1 AppImage on Centos7.

**Comment by csete** [comment]
Manually downloading the file will not help. Please check the messages (File -> Log browser) to see what errors occur.

**Comment by italic-r** [comment]
> Manually downloading the file will not help. Please check the messages (File -> Log browser) to see what errors occur.

Gotcha. The log is telling me it's an error with SSL CA cert:
```
2018/12/10 10:03:54|1|modes_update_from_network: Error fetching https://db.satnogs.org/api/modes/?format=json (Problem with the SSL CA cert (path? access rights?))
2018/12/10 10:03:54|1|modes_update_from_network: Could not fetch frequency files from network
2018/12/10 10:03:54|1|trsp_update_from_network: Error fetching https://db.satnogs.org/api/transmitters/?format=json (Problem with the SSL CA cert (path? access rights?))
2018/12/10 10:03:54|1|trsp_update_from_network: Could not fetch frequency files from network
```

**Comment by csete** [comment]
I suspect you are missing some SSL related package or certificates to be installed, though I'm not sure.

Can you try to see whether you get the same error if you are trying to fetch the file using the curl command line utility? If yes, you can try to search for a solution for Centos7.

**Comment by italic-r** [comment]
> Can you try to see whether you get the same error if you are trying to fetch the file using the curl command line utility? If yes, you can try to search for a solution for Centos7.

I tried out various security configurations and found interesting results.  
`curl https://db.satnogs.org/api/modes/?format=json` results in a json output.  
Using the `-2` flag to force SSLv2 results in `curl: (35) SSL version range is not valid.`  
Using the `-3` flag to force SSLv3 returns `curl: (35) Cannot communicate securely with peer: no common encryption algorithm(s).`  
Using any of the `--tlsv1` related flags results in json output.

Just to be thorough, my curl and libcurl versions are `7.29.0-51.el7` x86_64. In the meantime I will look for solutions to the failing `-3` flag.

**Comment by Logistix84** [comment]
Hi everyone! I have problem with show transponder's data in Gpredict version 2.3.37
There's no transponder data like on screenshot upper. Here is a screenshot of logs https://yadi.sk/i/ee7oSeFEUnD9Tw

**Comment by LongnoseRob** [comment]
@Logistix84 What I always do after updating my TLEs or the transponder data, is to close the module or restart gpredict.
I am not sure if this would also help in you case, but it might be worth a try.

Is this only problem only occuring wiht the ISS (Catalog No 25544) or also with other sats?
