### ISSUE TITLE
Time controller freezes on Win7

### ISSUE THREAD

**Issue by pcotret** [csete/gpredict#16]
On my laptop (Win7 64 bits), the time controller freezes each time I want to move to a prior or future day. Here is my "method" to make this happen:
- Open the time controller.
- Stop it.
- Move (for instance) to the next day.
- Win7 freezes :(

Here is a screenshot that may help. Everything is written in French but this is what I called a "freeze".

![sans titre](https://cloud.githubusercontent.com/assets/404135/12894449/0f3e5a1a-ce97-11e5-8f37-c8c2be947a02.png)

**Comment by csete** [comment]
For anything not directly related to this personal copy of gpredict, please use the official project page: https://sourceforge.net/projects/gpredict/

Author of windows binaries may still be around there.
