### ISSUE TITLE
Feature request: Moving ground station

### ISSUE THREAD

**Issue by marcoamm** [csete/gpredict#166]
For Low-Earth Orbit (LEO) satellites, ground and airborne vehicles, predicting satellite line of sight might be a interesting feature. This is available in expensive proprietary software, and I believe could add a lot of value for gpredict.

An example would be a long haul flight, depending on Galileo satellites to send search-and-rescue messages trough their service (https://www.gsa.europa.eu/european-gnss/galileo/services/galileo-search-and-rescue-sar-service)

**Comment by csete** [comment]
There is work in progress to have location input from GPS, see issue #2. It is enabled automatically at compile time if libgps-dev is installed. As you can see, this has been initiated back in 2010, so the interest has been rather limited.

Perhaps some of those entities who might be saving money on not having to buy expensive proprietary software could contribute to finishing it. Even though gpredict is free to download, somebody still has to spend time and money on implementing these things.
