### ISSUE TITLE
There is an error in the station location list

### ISSUE THREAD

**Issue by SHRS79** [csete/gpredict#175]
I must point out a very serious mistake. In the list of locations, Hong Kong, Taiwan, Macau and China are all listed as countries. These three regions belong to the People's Republic of China. Please correct this error.Thinks!

**Comment by csete** [comment]
We only use the term "Location" in the user interface and there is nothing saying whether an entry is a country, region or something else. While most of of the entries are organized by continent → country → city, there are also deviations. For example, both USA and Canada are listed at top-level together with continents.
