### ISSUE TITLE
Please update Ubuntu PPA with latest version 2.3.x builds

### ISSUE THREAD

**Issue by mark-orion** [csete/gpredict#186]
I notice that the Ubuntu PPA is still on version 2.2.1. It would be great to be able to run the latest GPredict versions on Ubuntu 18.04.

**Comment by csete** [comment]
The latest officially released version is 2.2.1. Version 2.3 refers to the development series and is not an official release tag. As much as I love the concept of "release often" I do not have the time to test, package, and support frequent development snapshots at this time. I can do that later when I will focus on gpredict, but right now I have too much work and other projects to work on.

**Comment by mark-orion** [comment]
>  I can do that later when I will focus on gpredict, but right now I have too much work and other projects to work on.

You have my sympathy - similar situation here. Thanks for all the work !

**Comment by csete** [comment]
The PPA will be updated as part of the release process when we have a release.
