### ISSUE TITLE
Will not download latest TLEs.

### ISSUE THREAD

**Issue by masterplayer30** [csete/gpredict#189]
Using GPredict via flatpak and it will not download any TLE data at all. PLEASE FIX!

**Comment by csete** [comment]
Nobody can fix anything with such little information.

**Comment by masterplayer30** [comment]
I have the latest version of GPredict and I have been trying to get TLE data only to get no data at all. I tried uninstalling and reinstalling still returned red. I even tried it ten times to update and still can't. This is got to be fixed.

**Comment by masterplayer30** [comment]
Forgot to add using Ubuntu 18.04 as well.

**Comment by csete** [comment]
Try https://launchpad.net/~gpredict-team/+archive/ubuntu/ppa

**Comment by masterplayer30** [comment]
I even tried the repo version and the Flatpak version both returned failed.
