### ISSUE TITLE
Will not download and TLEs at all.

### ISSUE THREAD

**Issue by masterplayer30** [csete/gpredict#190]
I have the latest version of GPredict and I have been trying to get TLE data only to get no data at all. I tried uninstalling and reinstalling still returned red. I even tried it ten times to update and still can't. This is got to be fixed. Using Ubuntu 18.04 as well.

**Comment by dongsin-kim** [comment]
Hi @masterplayer30 ,

Do you still have this problem?

I also use the version:
-  Ubuntu 18.04
-  Gpredict 2.2.1

Have you tried [Edit] - [Update TLE data from network]?
