### ISSUE TITLE
How useless gpredict is

### ISSUE THREAD

**Issue by pb2888** [csete/gpredict#208]
Hamlib 3.3 doesnt work in windows and irs useless in linux where gpredict should be made to use other proticols like omnirig which DOES WORK,for doin anythung at all with gpredict is a oain due to havung to be a programmer to even try and get it to work due to all the commands and various other shit that has to be tyoed in terminal or cmd everytime when it should create its own script for controlling radios and rotators so in the mean time it cant be used for portable sat comms

**Comment by csete** [comment]
Dear @pb2888 
Thanks for the feedback. I really appreciate the fact that you went through all the trouble of creating a GitHub account just to provide us some feedback.
