### ISSUE TITLE
Any way to get raw tracking data without rotctld ?

### ISSUE THREAD

**Issue by SharkEzz** [csete/gpredict#210]
Hi !

I'm currently trying to get the raw tracking data of the satellite (elevation and so) without using rotctld to process them later.

Is there any way to do that ? I've tried to make a "false" TCP server that Gpredict connect to using but it seems that it wait for some specific rotctld data (that I don't have) leading to a crash of Gpredict.

Thanks in advance for your help :+1:

**Comment by csete** [comment]
Hi,

The rotctld protocol documented in the rotctld manual, see e.g. http://manpages.ubuntu.com/manpages/xenial/man8/rotctld.8.html

If you need further technical support, please use a technical support forum, for Gpredict you can find the options here: http://gpredict.oz9aec.net/User_Support.php

We use GitHub for development only and not for support.
