### ISSUE TITLE
Gpredict fails to build with GCC 10

### ISSUE THREAD

**Issue by csete** [csete/gpredict#213]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957302

**Comment by reinerh** [comment]
It's now building with GCC 10 since #195 has been fixed.

**Comment by df7cb** [comment]
Debian package updated with a new git snapshot. A new proper release would be appreciated, though.
Thanks! (And this issue can be closed.)

**Comment by csete** [comment]
Thanks for the updates. I have forgotten about #113 
I will try to make a new release very soon.
