### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by Vinz87** [csete/gpredict#232]
I struggled finding the data/config folder after a Macports install; I finally found it in ~/.config/gpredict.

I would suggest to add this information in the Github readme, in order to let users manage for example custom satellite categories files.

**Comment by csete** [comment]
Thanks for suggestion. The plan has always been that everything should be editable from within the user interface and this is still the goal. The readme is only intended for very quick and basic info, everything else should go to the user manual.
