### ISSUE TITLE
[Feature request] Compability with GPS and magnetometer

### ISSUE THREAD

**Issue by Supermagnum** [csete/gpredict#234]
I think that Gpredict could benefit from the possibility to read information from a GPS and a magnetometer.
That could be used to find Nort automatically, and adjust the antennas azimuth accordingly.
That could be useful for those who are operating mobile/portable setups.

A nice unit is a Ozzmaker BerryGPS-IMU V3

https://ozzmaker.com/product/berrygps-imu/

It can be used in combination with Pirotator, located:
https://github.com/Supermagnum/Pirotator

**Comment by csete** [comment]
Thanks for the suggestions, however, The functionality and benefits you describe do not belong in gpredict but in the antenna rotator hardware and/or controller. Gpredict is only concerned with the satellite tracking functionality, i.e. calculating the satellite position, sending it to the rotator controller, and reading back the current position from the controller. IT's up to the controller to figure out where the antenna is pointing.
