### ISSUE TITLE
Cut new release?

### ISSUE THREAD

**Issue by sielicki** [csete/gpredict#249]
Hi,

Flathub provides a flatpak build of gpredict. We'd like to upgrade the Gnome SDK that it is built with, as we're currently using 3.34 (which is now end-of-life). 

gpredict, when checked out from git, will build just fine on newer Gnome SDKs. But the current release (tagged back in 2018) of gpredict will not.

Is it possible you might be willing to cut a new release? It would help us out.

See this discussion for details: https://github.com/flathub/net.oz9aec.Gpredict/pull/5

Thanks much,

**Comment by csete** [comment]
Could you use the current git head and version number 2.3.100 (generated by git describe)? The code is stable as such but there is some unfinished stuff that I'd like to finish before making an official release.
