### ISSUE TITLE
Building doesn't work when following README instructions

### ISSUE THREAD

**Issue by tomcass240** [csete/gpredict#256]
When trying to build from source by following the instructions in the readme file, it says to extract the source and run ./configure. I can't find any file called "configure" so typing ./configure doesn't do anything but there is a file called "configure.ac" in the folder. I'm pretty new to Linux and after doing some reading I found out I needed to type "autoconf" instead of ./configure. Unless I did something wrong I think the README file might need updating.

**Comment by mdblack98** [comment]
Actually "autoreconf -i" is the correct thing to do.
Mike W9MDB

 

    On Tuesday, April 13, 2021, 02:35:22 PM CDT, tomcass240 ***@***.***> wrote:  
 
 


When trying to build from source by following the instructions in the readme file, it says to extract the source and run ./configure. I can't find any file called "configure" so typing ./configure doesn't do anything but there is a file called "configure.ac" in the folder. I'm pretty new to Linux and after doing some reading I found out I needed to type "autoconf" instead of ./configure. Unless I did something wrong I think the README file might need updating.

**Comment by davidfdzp** [comment]
I had the same issue and I read somewhere that if you are building directly from the git repository, you have to run
./autogen.sh instead of configure. You can pass the same options to the autogen.sh script as you would to the configure script.
Certainly, updating the README would nice.

**Comment by csete** [comment]
@davidfdzp is correct and the info comes from the README ;)
https://github.com/csete/gpredict/blob/master/README#L65

I think what is confusing is that GitHub automatically generates tar.gz and zip source packages called "Source code", which are a copy of the git repository, hence they do not have the configure script. The official release packages have a version number in the file name, i.e. gpredict-2.2.1.tar.bz2, and these packages come with the configure script.

I think the README is correct, however, if anybody can think of a better or clearer way to write it, please let me know.

**Comment by mdblack98** [comment]
I've got the same problem with hamlib....I wonder why we don't just include the configure file in the github project to avoid this problem.That would prevent people from needing all the additional tools to compile things.

Mike W9MDB



 

    On Wednesday, April 14, 2021, 07:59:00 AM CDT, Alexandru Csete ***@***.***> wrote:  
 
 


@davidfdzp is correct and the info comes from the README ;)
https://github.com/csete/gpredict/blob/master/README#L65

I think what is confusing is that GitHub automatically generates tar.gz and zip source packages called "Source code", which are a copy of the git repository, hence they do not have the configure script. The official release packages have a version number in the file name, i.e. gpredict-2.2.1.tar.bz2, and these packages come with the configure script.

I think the README is correct, however, if anybody can think of a better or clearer way to write it, please let me know.

**Comment by csete** [comment]
> 've got the same problem with hamlib....I wonder why we don't just include the configure file in the github project to avoid this problem.That would prevent people from needing all the additional tools to compile things.

I think the configure file would change quite often when different developers build on different machines and it would be confusing when to check it and when not to check it in.

**Comment by mdblack98** [comment]
Yeah...I've decided against that one...it needs numerous other files to go with it.

 

    On Saturday, April 17, 2021, 10:44:58 AM CDT, Alexandru Csete ***@***.***> wrote:  
 
 



've got the same problem with hamlib....I wonder why we don't just include the configure file in the github project to avoid this problem.That would prevent people from needing all the additional tools to compile things.


I think the configure file would change quite often when different developers build on different machines and it would be confusing when to check it and when not to check it in.
