### ISSUE TITLE
support for  800 x 480 resolution touchscreen

### ISSUE THREAD

**Issue by wuxx** [csete/gpredict#267]
Hello, I'm using a raspberry pi with a 800 x 480 resoution 4.3 inch CSI touchscreen, it's tiny and I think good to be a outside station, we can use the touchscreen to open the gpredict , use the raspberry pi GPIO to control the radio and rotator, but unfortunately it seems the gpredict do not support the resolution 800 x 480 very well, for example I can not add a new ground station (I know there is a ok button, but  I can't see it ). which part of code can I try to fix it ? I would like to have a try
![rpi-4 3inch](https://user-images.githubusercontent.com/1648489/122061740-5fb6f300-ce21-11eb-99d4-97b8dc6fedc6.png)

**Comment by mdblack98** [comment]
Seems you can set up a virtual desktop and scroll...
https://raspberrypi.stackexchange.com/questions/95738/virtual-resolution-scrolling

Mike W9MDB 

    On Tuesday, June 15, 2021, 08:34:20 AM CDT, wuxx ***@***.***> wrote:  
 
 


Hello, I'm using a raspberry pi with a 800 x 480 resoution 4.3 inch CSI touchscreen, it's tiny and I think good to be a outside station, we can use the touchscreen to open the gpredict , use the raspberry pi GPIO to control the radio and rotator, but unfortunately it seems the gpredict do not support the resolution 800 x 480 very well, for example I can not add a new ground station. which part of code can I try to fix it ? I would like to have a try

**Comment by wuxx** [comment]
Thanks Mike! I update the framebuffer parameters in /boot/config.txt, now it works very well ! will close the issue
framebuffer_width=1600
framebuffer_height=960
![rpi-4 3inch](https://user-images.githubusercontent.com/1648489/122145051-1e592e80-ce87-11eb-8cc6-166b5fc58550.jpg)
