### ISSUE TITLE
Log level is debug always.

### ISSUE THREAD

**Issue by kukabu** [csete/gpredict#27]
Hello

I can't set the log level.

**Comment by kukabu** [comment]
It seems that something happened to the save/restore of variables. Lots of variable I can't save/restore.
Also I see lots of similar messages:
(gpredict:20055): GLib-CRITICAL **: g_key_file_get_boolean: assertion 'group_name != NULL' failed
(gpredict:20055): GLib-CRITICAL **: g_key_file_set_value: assertion 'g_key_file_is_group_name (group_name)' failed

**Comment by csete** [comment]
I also see the messages but I did not have time to look into it. Please consider gpredict as highly experimental at the moment as we re-write significant parts of it.
