### ISSUE TITLE
James Webb Space Telescope tracking causes app to freeze

### ISSUE THREAD

**Issue by rt-bishop** [csete/gpredict#280]
I've just found out that addition of JWST, Norad ID 50463, to the tracking list leads to a complete Gpredict freeze. I also checked my Look4Sat on Android and the n2yo.com website and both show crazy weird data. Do you possibly know the reason for this?
P.S. To restore the app function simply remove the satellite ID from ~/.config/Gpredict/*.mod file.

**Comment by yashi** [comment]
Would you mind sharing how to reproduce?  I thought I successfully did the other day but when I tried this morning I just worked.  I could be with a certain TLE parameters?

**Comment by rt-bishop** [comment]
@yashi, thanks for your response! You're right, I've just tried it and it doesn't crash, so I guess it was just some faulty TLE data.

**Comment by yashi** [comment]
Glad it works for you.
I guess we have some issue in Gpredict. It's unfortunate that we can't reproduce anymore.

**Comment by patyizsolt** [comment]
####
