### ISSUE TITLE
icom_rig_open: rig error getting frequency retry=0, err=Invalid parameter with IC-9700

### ISSUE THREAD

**Issue by dl2sba** [csete/gpredict#289]
Hello

I failed even at the first step. I'm using HAMLIB 4.4 on GERMAN Windows10 together with an IC-9700.

IC-9700 has FW: 
-    Main 1.31
-    Sub+Front CPU 1.00

Rig is set up as described here: https://github.com/csete/gpredict/blob/master/doc/notes/ic-9700.txt

I get "**icom_rig_open: rig error getting frequency retry=0, err=Invalid parameter**" right after start.  
I can see the frequency response from the radio - but then rigctl shows errors ...

Any help is appreciated

//Dietmar
  
[rigctld.log](https://github.com/csete/gpredict/files/8777076/rigctld.log)

**Comment by mdblack98** [comment]
Download the latest here
http://n0nb.users.sourceforge.net/

Mike W9MDB

 

    On Thursday, May 26, 2022, 02:19:14 AM CDT, Dietmar, DL2SBA ***@***.***> wrote:  
 
 


Hello

I failed even at the first step. I'm using HAMLIB 4.4 on Windows10 together with an IC-9700.

IC-9700 has FW:
   
   - Main 1.31
   - Sub+Front CPU 1.00

I get "icom_rig_open: rig error getting frequency retry=0, err=Invalid parameter" right after start.
I can see the frequency response from the radio - but then rigctl shows errors ...

Any help is appreciated

//Dietmar

rigctld.log
