### ISSUE TITLE
TEVEL-6 sat missing

### ISSUE THREAD

**Issue by shepherd007** [csete/gpredict#338]
**Gpredict version:** 2.3.37
**OS:** Windows 10

I cannot select TEVEL-6 as a satellite to track. There are TEVEL-1 to TEVEL-5 and TEVEL-7 to TEVEL-8 available.
I already tried updating TLE file from network - and uploading locally TLE file downloaded from:
http://celestrak.org/NORAD/elements/gp.php?GROUP=amateur&FORMAT=tle

Anyone has seen this issue?

**Comment by mdblack98** [comment]
You don't show this list in the Configure page?


Mike W9MDB
 

    On Monday, November 27, 2023 at 08:42:51 AM CST, shepherd007 ***@***.***> wrote:  
 
 


Gpredict version: 2.3.37
OS: Windows 10

I cannot select TEVEL-6 as a satellite to track. There are TEVEL-1 to TEVEL-5 and TEVEL-7 to TEVEL-8 available.
I already tried updating TLE file from network - and uploading locally TLE file downloaded from:
http://celestrak.org/NORAD/elements/gp.php?GROUP=amateur&FORMAT=tle

Anyone has seen this issue?

**Comment by shepherd007** [comment]
> You don't show this list in the Configure page? Mike W9MDB On Monday, November 27, 2023 at 08:42:51 AM CST, shepherd007 ***@***.***> wrote: Gpredict version: 2.3.37 OS: Windows 10 I cannot select TEVEL-6 as a satellite to track. There are TEVEL-1 to TEVEL-5 and TEVEL-7 to TEVEL-8 available. I already tried updating TLE file from network - and uploading locally TLE file downloaded from: http://celestrak.org/NORAD/elements/gp.php?GROUP=amateur&FORMAT=tle Anyone has seen this issue? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

When I enter "Configure" there is no TEVEL-6 satellite available (see attached screenshot):

![configure](https://github.com/csete/gpredict/assets/1681940/6bc27d11-1f88-4db2-9037-ac3731306172)

**Comment by mdblack98** [comment]
See if you have this file in your GPredict data store


C:\Users\mdbla\Gpredict\satdata> more .\50999.sat
[Satellite]
VERSION=1.1
NAME=Tevel-6
NICKNAME=Tevel-6
TLE1=1 50999U 22002R   23331.15431418  .00038335  00000+0  10890-2 0  9998
TLE2=2 50999  97.4133  38.4015 0006963  16.9632 343.1843 15.36058328103712
STATUS=0









On Monday, November 27, 2023 at 09:00:05 AM CST, shepherd007 ***@***.***> wrote: 







>  
> You don't show this list in the Configure page? Mike W9MDB On Monday, November 27, 2023 at 08:42:51 AM CST, shepherd007 @.> wrote: Gpredict version: 2.3.37 OS: Windows 10 I cannot select TEVEL-6 as a satellite to track. There are TEVEL-1 to TEVEL-5 and TEVEL-7 to TEVEL-8 available. I already tried updating TLE file from network - and uploading locally TLE file downloaded from: http://celestrak.org/NORAD/elements/gp.php?GROUP=amateur&FORMAT=tle Anyone has seen this issue? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>
> 

When I enter "Configure" there is no TEVEL-6 satellite available (see attached screenshot):

configure.JPG (view on web)
