### ISSUE TITLE
The high/low frequency issue.

### ISSUE THREAD

**Issue by kukabu** [csete/gpredict#35]
Hello

Some satellite in SatNOGS DB have only UP_HIGH/DOWN_HIGH and gpredict doesn't work with it.
Is it a bug in SatNOGS DB or gpredict?

https://db.satnogs.org/satellite/41313/

**Comment by kukabu** [comment]
hm... I found the same in local files https://github.com/csete/gpredict/blob/master/data/trsp/25509.trsp

**Comment by LongnoseRob** [comment]
Did you try this whis the latest version?
I also found some issues with the satelite data and it was fixed already..

Maybe reimporting the TRSP data from SatNogs will help..

**Comment by kukabu** [comment]
the latest version

**Comment by csete** [comment]
Thanks for the info.

Previously trsp files were created manually and validated before becoming integral part of the package. Now we are in a new situation where data comes from external sources and we have to be able to handle all sorts of data.

I am in the process of cleaning up the side effects of the new trsp importer and also change the way we manage frequency data internally, but I am going to need some time to finish. But keep posting issues you find.

**Comment by csete** [comment]
Please try it now. The code should now be robust for various missing parts of transponder data. You are also welcome to test it with manually edited files.

It was a late night commit but I hope I didn't ruin anything :-)

**Comment by kukabu** [comment]
Fixed. Thank!
