### ISSUE TITLE
Arch linux : segmentation fault (core dumped)  gpredict

### ISSUE THREAD

**Issue by hamdyaea** [csete/gpredict#350]
I have this error on Arch Linux : 

segmentation fault (core dumped)  gpredict

[gpredict_strace.txt](https://github.com/csete/gpredict/files/14397296/gpredict_strace.txt)

I send a file with the result of strace commande  :  strace gpredict 2>&1

**Comment by mdblack98** [comment]
The file says
zsh: command not found: strace


 

    On Sunday, February 25, 2024 at 12:01:04 PM CST, Hamdy Abou El Anein ***@***.***> wrote:  
 
 


I have this error on Arch Linux :

segmentation fault (core dumped) gpredict

gpredict_strace.txt

I send a file with the result of strace commande : strace gpredict 2>&1

**Comment by hamdyaea** [comment]
If that can help someone, I have solved the issue with uninstalling Gpredict, all configs files in /home/user/config/ etc..  Then I have reinstalled it and everything was OK.
