### ISSUE TITLE
autotrack does not update radio control

### ISSUE THREAD

**Issue by LongnoseRob** [csete/gpredict#61]
with GPREDICT 1.3.460-6fc0-dirty:

activating autotrack before radio control still works as intended.
however starting radio control and then selecting autotrack does not update the sat selection in radio control.

could this be caused by the latest changes regarding threading?

**Comment by csete** [comment]
The new threading is in the testing branch for now, so that's not it. I suspect this is just how it was implemented.

**Comment by LongnoseRob** [comment]
@csete thanks for the explanation,

Please excuse the noise, I`ll close this issue.

**Comment by csete** [comment]
Well, if it behaves the way you describe then it is a bug for sure. All I meant was that this is probably how it has been since the implementation (without knowing for sure), but we should most certainly look into fixing it.

**Comment by DL4PD** [comment]
Tested in 2.0:
This is not reproducable for me.

**Comment by csete** [comment]
Thanks @DL4PD - I guess you fixed it when you rewrote the controller ;-)

@LongnoseRob : any chance you could test it and confirm that it now works as it should?

**Comment by LongnoseRob** [comment]
@csete undtunately I am not setup for testing this at the moment.
I would propose to close it

**Comment by csete** [comment]
Ok, please let us know if you encounter it again.
