### ISSUE TITLE
Port Mismatch with gqrx remote control 

### ISSUE THREAD

**Issue by vk4tec** [csete/gpredict#71]
I was debugging a connection issue between gpredict and gqrx

The gqrx website and software says use port 7356

http://gqrx.dk/doc/remote-control

When I run up gpredict it is hard coded to port 4532

I used wireshark on localhost to spot this port mismatch

Can we align the two as to not confuse people

I am writing a gpredict to ICOM CIV program

Andrew VK4TEC

**Comment by vk4tec** [comment]
my gpredict reports version 1.3 - is that the latest - I am trying to tell from GitHub 

Andrew

**Comment by vk4tec** [comment]
MacBook:~ vk4tec$ sudo port uninstall gpredict
Password:
--->  Deactivating gpredict @1.3_2
--->  Cleaning gpredict
--->  Uninstalling gpredict @1.3_2
--->  Cleaning gpredict

Test for macports version - 23 Aug 2017

**Comment by vk4tec** [comment]
MacBook:src vk4tec$ grep 4532 *
grep: nxjson: Is a directory
sat-pref-rig-editor.c:    gtk_spin_button_set_value(GTK_SPIN_BUTTON(port), 4532);
sat-pref-rig-editor.c:        gtk_spin_button_set_value(GTK_SPIN_BUTTON(port), 4532); /* hamlib default? */
sat-pref-rig-editor.c:    gtk_spin_button_set_value(GTK_SPIN_BUTTON(port), 4532);     /* hamlib default? */
sat-pref-rig.c:        .port = 4532,
sat-pref-rig.c:        .port = 4532,
sat-pref-rig.c:        .port = 4532,
grep: sgpsdp: Is a directory

**Comment by csete** [comment]
You can use whatever port you want now
