### ISSUE TITLE
Additions to manual about installation MAC OS X 

### ISSUE THREAD

**Issue by vk4tec** [csete/gpredict#72]
Hello 

I found some issues with the install 

On MAC OS X, if you download the source using ZIP download you run into issues.

I used git instead of ZIP download and got success

Also git has to be run as root 

sudo git clone < source.git >

cd gpredict 

I then had to do a 'chmod 777 *'

The next command is './configure.ac' not './configure'

And then it bombs out 

MacBook:gpredict vk4tec$ ./configure.ac 
./configure.ac: line 1: syntax error near unexpected token `[gpredict],'
./configure.ac: line 1: `AC_INIT([gpredict],'
MacBook:gpredict vk4tec$ 

Andrew Aug 2017 VK4TEC

**Comment by csete** [comment]
Gpredict on Mac OS X is only available as a third party package (e.g. macports), so I can't help with that.

Having said that, what you are trying to do is wrong. You are not supposed to execute the configure.ac file. As it is written in the README:

> If you are building from the git repository and there is no configure script,
> run ./autogen.sh instead. You can pass the same options to the autogen.sh
> script as you would to the configure script.
