### ISSUE TITLE
Add ICOM CIV control

### ISSUE THREAD

**Issue by vk4tec** [csete/gpredict#76]
Because gpredict does not support serial port doppler correction for an ICOM radio I am forced to use macdoppler that does.

**Comment by LongnoseRob** [comment]
Have you checked if rigctld could control your rig?
Then you could connect gpredict by network to rigctld..

(Sent from my mobile device)

**Comment by csete** [comment]
Like @LongnoseRob said, gpredict uses hamlib to handle the radio specific interfacing, including ICOM CIV. So, if the hamlib rigctl utility can control your radio, then you can also control it from gpredict through  the rigctld daemon.

The user manual has more info about setting it up and testing it, see https://sourceforge.net/projects/gpredict/files/Gpredict/1.3/
