### ISSUE TITLE
Windows: Radio interface shows port 7356 , uses port 7777

### ISSUE THREAD

**Issue by vk4tec** [csete/gpredict#77]
I was experimenting with gpredict under windows 10 towards my macpc

I set a radio interface on port 7777 then used 7356 

The radio interface showed as using port 7356 but wirshark traces show 7777 in use

I am unsure why gpredict hung onto the original port 7777 I was testing on 

Please test by cycling Radio interface port and network traces on "engage" button 

Andrew VK4TEC

**Comment by csete** [comment]
Have no idea how this can happen. Is this still an issue with the latest windows snapshot?
https://github.com/csete/gpredict/releases/download/v2.3/gpredict-win32-2.3.37.zip
