### ISSUE TITLE
Problem starting Gpredict 1.3

### ISSUE THREAD

**Issue by naydden** [csete/gpredict#83]
Gpredict stopped working for me. I am wondering where is the issue and how should I solve it. 
As soon as I start gpredict, it ends with a "Segmentation fault (core dumped)" message.

My system is an Ubuntu 16.04.3 LTS (Xenial Xerus).

Next, I attach the gdb trace:

> Thread 1 "gpredict" received signal SIGSEGV, Segmentation fault.
Checksum_Good (tle_set=0x0, tle_set@entry=0x2841ab4d570a9000 <error: Cannot access memory at address 0x2841ab4d570a9000>) at sgpsdp/sgp_in.c:59
59			if ( (tle_set[i] >= '0') && (tle_set[i] <= '9') )

Thanks in advance!

**Comment by csete** [comment]
We are about to release version 2.0 and I don't wish to spend time on debugging this ancient release. There will be packages in our PPA.
