### ISSUE TITLE
Unexplained options in Satlist

### ISSUE THREAD

**Issue by zxa** [csete/gpredict#86]
Maybe not a real "issue": In the preferences for the satellite list there are the options "Decay" and "BOLD" with no tooltips. In the satlist Decay seems to be "True" all the time and Bold is 400 for not visible sats and 700 for visible. What do these values tell me?

**Comment by csete** [comment]
I think BOLD was added in relation to highlighting satellites above the horizon. I don't remember why it was done this way and maybe we can do it better. It's probably a similar story with decay. In any case they should not be shown in the configuration

**Comment by csete** [comment]
Ok, it should be fixed now. The BOLD field is no longer shown
