### ISSUE TITLE
Time Controller will not work in December

### ISSUE THREAD

**Issue by drotor** [csete/gpredict#90]
When trying to change the date or time in the month of December using the Time Controller, the month jumps to January in the main window and the satellite positions change to the January positions set in the Time Controller which still shows the requested month of December.

**Comment by csete** [comment]
Thanks for reporting, I will take a look. There is also another open issue with the time controller.

**Comment by csete** [comment]
Hm, I can't reproduce this. Could you post a screenshot showing your main window and time controller?

**Comment by kossy944** [comment]
I can confirm this issue too. When trying to select the next day of December in the time controller window, Gpredict month jumps to January as drotor commented previously. Please see screenshot.
![gpredict_time_controller_issue](https://user-images.githubusercontent.com/8768706/34344782-4bfa874e-ea24-11e7-8acb-faf11b738fe6.png)

**Comment by csete** [comment]
THanks @kossy944, is this with the 2.0 release?

**Comment by kossy944** [comment]
yes, version 2.0

![gpredict_time_controller_issue_version](https://user-images.githubusercontent.com/8768706/34352977-84fe2046-ea60-11e7-9275-f061eaf03917.png)

**Comment by csete** [comment]
Ok, thanks. I can now reproduce the error. The hint was 10 AM on your screenshot suggesting that you are using local time instead if UTC. And indeed, selecting "Show local time" in the configuration has this problem, but not UTC.

Thanks for the help, I will try and fix it for the next release.

**Comment by kossy944** [comment]
Yes, UTC works as expected with the time-controller window when you select the next day. 
I will just switch back to UTC.
Thanks :-)

![gpredict_time_controller_issue_utc](https://user-images.githubusercontent.com/8768706/34353473-53b84df6-ea63-11e7-90cf-319cb38e275b.png)

**Comment by csete** [comment]
A workaround will be available in the next release.
