### ISSUE TITLE
save-pass.c; Unrecognized character escape sequence

### ISSUE THREAD

**Issue by gvanem** [csete/gpredict#96]
When compiling `save-pass.c` using MSVC, I get these warnings:
```
save-pass.c(153): warning C4129: '(': unrecognized character escape sequence
save-pass.c(300): warning C4129: '(': unrecognized character escape sequence
```
I.e. for this string 
`savefile = g_strdelimit(savefile, "!?/\()*&%$#@[]{}=+<>,.|:;", '_'); `

It should be 
`savefile = g_strdelimit(savefile, "!?/\\()*&%$#@[]{}=+<>,.|:;", '_'); ` I suppose.

Strangely, neither gcc not clang-cl gives me any warning here.

PS. [Github](https://github.com/csete/gpredict/blame/master/src/save-pass.c#L153) thinks it's an illegal ESC-code too:
![gpredict_save-pass](https://user-images.githubusercontent.com/945271/33937257-0eaec11e-e003-11e7-844e-97fbf4185727.png)

**Comment by csete** [comment]
Thanks for the heads up. It should most certainly be \\\ 
I'm pushing a fix.
